### ISSUE TITLE
Args and kwargs errors when trying to sub

### ISSUE THREAD

**Issue by petedermott** [C0D1UM/django-nats-client#25]
Hi! First off, apologies if this is the wrong place to ask, if it is better to submit this elsewhere please let me know.

I'm trying to use `django-nats-client` within my project but I'm running into some issues with my relatively simple example.

I have a new django app called `nats_test` that has a `nats.py` file that looks like this:
```
import nats_client


@nats_client.register
def case_created(payload):
    print(payload)
```

I have add the app alongside `nats_client` to my `INSTALLED_APPS` in `settings.py`. I have also added configs to setup my server connection that is running outside of my docker container (nats-serve was installed via MacOS homebrew):
```
INSTALLED_APPS = (
    ...
    "nats_client",
    ...
    "nats_test",
)

NATS_SERVER = "nats://host.docker.internal:4222"
NATS_JETSTREAM_ENABLED = False
NATS_NAMESPACE = "nt"
```

I'm then usings the nats CLI to create a test message: `nats pub nt.case_created '{"payload": "yo", "args": "an_arg", "kwargs": {"some": "kwargs"}}' --server localhost:4222`

From my debugging it looks like `args` and `kwargs` are required - is this true? or is there a way to exclude them? What is the proper way to call this from the nats CLI?

**Comment by earthpyy** [comment]
Hi, the message payload should be in this format:

```json
{
  "args": [],
  "kwargs": {},
}
```

(`args` should be a list of arguments to pass to a function, and no `payload` key needed.)

So, your sample function could be called like this:

```json
{
  "args": ["yo"],
  "kwargs": {},
}
```

**Comment by earthpyy** [comment]
@petedermott Sorry for a very late reply. The latest version (0.4.3) should not requires both anymore.
